{ pkgs, inputs, config, ... }: {
    #hyprland = inputs.hyprland.packages.${pkgs.system}.hyprland;

    imports = [
        ./waybar.nix
        ./hyprlock.nix
    ];

    home.packages = with pkgs; [
        waybar # Bar
        dunst # Notif daemon
        libnotify # Needed by dunst
        kitty # Terminal
        #wofi # App launcher
        anyrun # App launcher

        hyprpaper # Wallpaper
        hyprshot # Screenshot
        hyprlock # Lock screen

        networkmanagerapplet # Wifi
        blueman # Bluetooth
        brightnessctl # Brightness keys
        
    ];

    wayland.windowManager.hyprland = {
        enable = true;
        settings = {
            autogenerated = "0";
            
            misc = {
                # This really should be default imo
                # It's confusing otherwise
                new_window_takes_over_fullscreen = 2;
            };

            #env = "XCURSOR_SIZE,50";

            ### MONITOR CONFIG ###
            # TODO: Make this work with desktop too (dynamic nix?)
            monitor = ",preferred,1920x1080@144,1";

            # Start up extra components
            exec-once = [
                "waybar & dunst & libnotify & hyperpaper & nm-applet & blueman-applet"
                "[workspace 1 silent] firefox"
                "[workspace 2 silent] code"
                "[workspace 3 silent] discord"
            ];

            # Definitions
            "$mainMod" = "SUPER";

            input = {
                kb_layout = "us";

                touchpad = {
                    natural_scroll = "yes";
                    disable_while_typing = false;
                };

                sensitivity = "0";
            };

            xwayland = {
                #force_zero_scaling = "true";
            };

            general = {
                gaps_in = "2";
                gaps_out = "10";
                border_size = "2";
                "col.active_border" = "rgba(33ccffee) rgba(00ff99ee) 45deg";
                "col.inactive_border" = "rgba(595959aa)";

                layout = "dwindle";

                # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
                allow_tearing = false;
            };

            decoration = {
                rounding = 5;
            };

            gestures = {
                workspace_swipe = true;
                workspace_swipe_fingers = 3;
            };

            animations = {
                enabled = "yes";
                animation = [
                    "workspaces,1,1,default"
                ];
            };

            bind = [
                #"$mainMod, W, exec, nm-applet"
                #"$mainMod, B, exec, blueman-applet"

                "$mainMod, C, exec, kitty"
                "$mainMod, Q, killactive, "
                "$mainMod, M, exit, "
                "$mainMod, E, exec, dolphin"
                "$mainMod, V, togglefloating, "
                "ALT, Space, exec, anyrun"
                "$mainMod, P, pseudo, # dwindle"
                "$mainMod, J, togglesplit, # dwindle"

                "$mainMod, L, exec, hyprlock"

                "$mainMod SHIFT, F, exec, firefox"
                "$mainMod SHIFT, P, exec, firefox --private-window"
                "$mainMod SHIFT, C, exec, code"
                

                # Screenshotting
                ", Print, exec, hyprshot -m region --clipboard-only"
                "SHIFT, Print, exec, hyprshot -m output --clipboard-only"

                # Brightness
                ",code:233, exec, brightnessctl set 5%+"
                ",code:232, exec, brightnessctl set 5%-"

                # Volume
                ",code:123, exec, wpctl set-volume -l 1.0 @DEFAULT_SINK@ 5%+"
                ",code:122, exec, wpctl set-volume -l 1.0 @DEFAULT_SINK@ 5%-"
                ",code:121, exec, wpctl set-volume -l 1.0 @DEFAULT_SINK@ 0%"

                # Move focus with mainMod + arrow keys
                "$mainMod, left, movefocus, l"
                "$mainMod, right, movefocus, r"
                "$mainMod, up, movefocus, u"
                "$mainMod, down, movefocus, d"

                "$mainMod, F, fullscreen, 1"
                "ALT, Tab, cyclenext,"
                #"ALT SHIFT, Tab, cycleprevious,"
                "$mainMod, Tab, workspace, e+1"
                "$mainMod SHIFT, Tab, workspace, e-1"

                # Switch workspaces with mainMod + [0-9]
                "$mainMod, 1, workspace, 1"
                "$mainMod, 2, workspace, 2"
                "$mainMod, 3, workspace, 3"
                "$mainMod, 4, workspace, 4"
                "$mainMod, 5, workspace, 5"
                "$mainMod, 6, workspace, 6"
                "$mainMod, 7, workspace, 7"
                "$mainMod, 8, workspace, 8"
                "$mainMod, 9, workspace, 9"
                "$mainMod, 0, workspace, 10"

                # Move active window to a workspace with mainMod + SHIFT + [0-9]"
                "$mainMod SHIFT, 1, movetoworkspace, 1"
                "$mainMod SHIFT, 2, movetoworkspace, 2"
                "$mainMod SHIFT, 3, movetoworkspace, 3"
                "$mainMod SHIFT, 4, movetoworkspace, 4"
                "$mainMod SHIFT, 5, movetoworkspace, 5"
                "$mainMod SHIFT, 6, movetoworkspace, 6"
                "$mainMod SHIFT, 7, movetoworkspace, 7"
                "$mainMod SHIFT, 8, movetoworkspace, 8"
                "$mainMod SHIFT, 9, movetoworkspace, 9"
                "$mainMod SHIFT, 0, movetoworkspace, 10"
            ];

            bindm = [
                # Move/resize windows with mainMod + LMB/RMB and dragging"
                "$mainMod, mouse:272, movewindow"
                "$mainMod, mouse:273, resizewindow"
            ];

            bindl = [
                ",switch:on:Lid Switch,exec,hyprlock"
            ];
        };
    };

    
    #home.file."hyprlock.conf".source = config.lib.file.mkOutOfStoreSymlink ../hypr/hyprlock.conf;
}
